### ISSUE TITLE
[RFC] Declarative format

### ISSUE THREAD

**Issue by akerouanton** [NiR-/docker-generator#2]
We need a declarative format in order to help developers to create custom containers for their project. The idea is to generate `Dockerfile` from this configuration with docker/security best practices enforced.

Other ideas:
- Add support for dev/prod environment ?
- Use `composer.json` to guess needed extensions.
- Support for multiple services (e.g. mysql/rabbitmq/memcache)
- Build container ? 

Example:

```
php:
  version: 5.6.2
  libraries: [] # Additional libraries
  php_ini: [] # Additional php.ini config
  php_fpm: [] # Additional php-fpm.ini config
  exts:
    gd: '*'
    gmp: '*'
    intl: '*'
    mbstring: '*'
    pcntl: '*'
    memcache: '*'
    amqp: '1.4.0'
    sundown: '0.3.11'
    exif: '*'
    pdo_mysql: '*'
    openssl: '*'
  extra_steps: # Add imperative steps in the generated dockerfile
    pre_apt: []
    pre_exts: []
    pre_config: []
    pre_copy: []

mysql:
    sql_mode: 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

memcache: true
redis: true
rabbitmq: true
```
